### ISSUE TITLE
Why we not load all the ipsum's options from the choosed ipsum, with Liquid?

### ISSUE THREAD

**Issue by ramon-src** [allipsum/allipsum.github.io#10]
My suggestion is:
Load the choosed Ipsum and all your languages types in a non-display div, structured with ids about the  lang type. Like a XML and Json structure, into HTML.
We will reduce the many requests and we won't need save into storage. 
The JavaScript only will manipulate the DOM. The process logic is slower no?
Like:

```html
<div id="phrase-container display-none">
    {% for language in page.language %}
        <div id="{{language.name}}">
            {% for text in language.text %}
                <p>{{ text }}</p>
            {% endfor %}
        </div>
     {% endfor %}
</div>
```

Example:
When the user click to generate many paragraphs, we will get in div with id lang the paragraphs loaded. Run a simple logic to copy and paste this values into an array, and show it. 

DilmesIpsum use a similiar logic. In he, they put the texts into a static array.

**Comment by Sena** [comment]
Lets create a Json like the jekyll tips http://jekyll.tips/jekyll-casts/jekyll-search-using-lunr-js/
